---
# Configure haproxy

- name: ensure haproxy allow lists
  template:
    src: haproxy.acl.j2
    dest: "/usr/local/etc/haproxy/{{ item.name }}-allowed.acl"
  with_items:
  - "{{ haproxy_allowlists }}"
  register: haproxy_allowlist_change

- name: ensure haproxy configuration
  template:
    src: haproxy.conf.j2
    dest: "{{ haproxy_path_prefix }}/etc/haproxy.conf"
  register: haproxy_config_change

