---
# Configure haproxy

- name: fetch haproxy uid / gid
  user:
    name: haproxy
  check_mode: True
  register: haproxy_user_res

- set_fact:
    haproxy_uid: "{{ haproxy_user_res.uid }}"
    haproxy_gid: "{{ haproxy_user_res.group }}"

- name: ensure map folder
  file:
    path: "{{ haproxy_map_folder }}"
    state: directory
  when: haproxy_maps 

- name: ensure haproxy configuration
  template:
    src: haproxy.conf.j2
    dest: "{{  haproxy_config_file }}"
  register: haproxy_config_change

