---

- name: ensure haproxy is installed
  package:
    name: "{{ haproxy_package }}"
    state: present

- name: ensure additional packages are installed
  package:
    name: "{{ haproxy_extra_packages }}"
    state: present

- name: ensure haproxy is enabled
  sysrc:
    name: "haproxy_enable"
    value: "YES"

- name: ensure haproxy user
  user:
    name: haproxy
    group: nobody
    create_home: no
    uid: "{{ haproxy_uid }}"
    system: yes
