---

- name: ensure haproxy is installed
  pkgng:
    name: "{{ haproxy_package }}"
    state: present
    jail: "{{ haproxy_jail_name | default(omit) }}"

- name: ensure additional packages are installed
  pkgng:
    name: "{{ haproxy_extra_packages }}"
    state: present
    jail: "{{ haproxy_jail_name | default(omit) }}"

- name: ensure additional packages are also on the host
  pkgng:
    name: "{{ haproxy_extra_packages }}"
    state: present

- name: ensure haproxy is enabled
  community.general.sysrc:
    path: "{{ haproxy_jail_location | default('/') }}/etc/rc.conf"
    name: "haproxy_enable"
    value: "YES"

- name: ensure haproxy_config for multiple config files
  community.general.sysrc:
     path: "{{ haproxy_jail_location | default('/') }}/etc/rc.conf"
     name: "haproxy_config"
     value: "{{ haproxy_config_folder }}"
  when: haproxy_multi_config
