---
# main task file

- include_tasks: install.yml
  tags:
  - install

- include_tasks: logging.yml
  tags:
  - logging
  - syslogd

- include_tasks: self_signed.yml
  tags:
  - certs
  - selfsigned

- include_tasks: configure.yml
  tags:
  - configuration

- include_tasks: reload.yml
  tags:
  - reload

