---
# main task file

- name: ensure OS specifics are included
  include_vars: "{{ item }}"
  with_first_found:
  - "{{ ansible_os_family }}.yml"

- include_tasks: "install-{{ ansible_os_family }}.yml"
  tags:
  - install

- include_tasks: "logging-{{ ansible_os_family }}.yml"
  tags:
  - logging
  - syslogd

- include_tasks: self_signed.yml
  tags:
  - certs
  - selfsigned

- include_tasks: configure.yml
  tags:
  - configuration

- include_tasks: "reload-{{ ansible_os_family }}.yml"
  tags:
  - reload

