---
# Reload haproxy

- name: Restart haproxy
  service:
    name: haproxy
    state: reloaded
  when: 'haproxy_config_change.changed or haproxy_allowlist_change.changed and haproxy_jail_name is not defined'

- name: Restart jailed haproxy
  command: "service -j {{ haproxy_jail_name }} haproxy restart"
  when: 'haproxy_jail_name is defined and (haproxy_config_change.changed  or haproxy_allowlist_change.changed)'
